// apps/ng-tracker/src/app/modules/tracker/components/task-item.component.ts
import { Component, computed, input, output, inject } from '@angular/core';
import { Task } from '@task-domain';
import { DatePipe, NgClass } from '@angular/common';
import { TaskService } from '../../../shared/services/task.service';
import { take } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { CardModule } from 'primeng/card';
import { TooltipModule } from 'primeng/tooltip';
import { ConfirmService } from '../../../shared/services/confirm.service';

@Component({
  selector: 'app-task-item',
  imports: [NgClass, ButtonModule, CardModule, TooltipModule, DatePipe],
  template: `
    <p-card
      data-test-id="task-card"
      [ngClass]="{
        reminder: task().reminder,
        'hover:shadow-xl': true,
        'transition-all': true,
        'duration-300': true,
        'cursor-pointer': true,
      }"
      [pTooltip]="'Tip: Double-click to toggle reminder'"
      tooltipPosition="top"
      (dblclick)="toggleReminder(taskSignal())"
      class="h-full"
    >
      <div class="flex justify-between items-start gap-4">
        <div class="flex-1 min-w-0">
          <h3
            class="text-lg font-semibold text-gray-800 dark:text-slate-100 mb-2 break-words"
          >
            {{ task().text }}
          </h3>
          <p
            class="text-sm text-gray-600 dark:text-slate-300 flex items-center gap-2"
          >
            <i class="pi pi-calendar text-blue-600 dark:text-blue-400"></i>
            {{ task().day | date: 'medium' }}
          </p>
          @if (task().reminder) {
            <div class="mt-2 flex items-center gap-2">
              <i class="pi pi-bell text-amber-500"></i>
              <span
                class="text-xs text-amber-600 dark:text-amber-400 font-medium"
                >Reminder Set</span
              >
            </div>
          }
        </div>
        <p-button
          data-test-id="delete-task"
          (click)="requestDelete(taskSignal())"
          icon="pi pi-times"
          [rounded]="true"
          [text]="true"
          severity="danger"
          [pTooltip]="'Delete task'"
          tooltipPosition="left"
          class="flex-shrink-0"
        />
      </div>
    </p-card>
  `,
})
export class TaskItemComponent {
  task = input.required<Task>();
  taskChanged = output<void>();
  taskSignal = computed(() => this.task());
  private readonly confirm = inject(ConfirmService);

  constructor(private readonly taskService: TaskService) {}

  requestDelete(task: Task): void {
    this.confirm
      .confirm({
        title: 'Confirm deletion',
        message: `Delete task "${task.text}"? This action cannot be undone.`,
        acceptLabel: 'Delete',
        rejectLabel: 'Cancel',
        severity: 'danger',
      })
      .then((ok) => {
        if (!ok) return;
        this.taskService
          .deleteTask(task)
          .pipe(take(1))
          .subscribe(() => {
            this.taskChanged.emit();
          });
      });
  }

  toggleReminder(task: Task): void {
    task.reminder = !task.reminder;
    const updatedTask = { ...task, reminder: task.reminder };
    this.taskService.updateTaskReminder(updatedTask).pipe(take(1)).subscribe();
  }
}

// apps/vue-tracker/src/components/tasks/TaskItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import Card from 'primevue/card';
import Button from 'primevue/button';
import { taskService } from '../../services/task.service';
import { useConfirmService } from '../../composables/useConfirm';
import type { Task } from '@task-domain';

const props = defineProps<{
  task: Task;
}>();

const emit = defineEmits<{
  taskChanged: [];
}>();

const { showConfirm } = useConfirmService();

const reminderClass = computed(() => ({
  reminder: props.task.reminder,
  'hover:shadow-xl': true,
  'transition-all': true,
  'duration-300': true,
  'cursor-pointer': true,
}));

const deleteTask = async () => {
  const confirmed = await showConfirm({
    title: 'Confirm deletion',
    message: `Delete task "${props.task.text}"? This action cannot be undone.`,
    acceptLabel: 'Delete',
    rejectLabel: 'Cancel',
    severity: 'danger',
  });

  if (!confirmed) return;

  try {
    await taskService.deleteTask(props.task);
    emit('taskChanged');
  } catch (error) {
    console.error('Failed to delete task:', error);
  }
};

const toggleReminder = async () => {
  const updatedTask = { ...props.task, reminder: !props.task.reminder };
  try {
    await taskService.updateTaskReminder(updatedTask);
    emit('taskChanged');
  } catch (error) {
    console.error('Failed to update reminder:', error);
  }
};

const formatDate = (date: string) => {
  if (!date) return '';
  return new Date(date).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};
</script>

<template>
  <Card :class="reminderClass" @dblclick="toggleReminder" v-tooltip.top="'Tip: Double-click to toggle reminder'">
    <template #content>
      <div class="flex justify-between items-start gap-4">
        <div class="flex-1 min-w-0">
          <h3 class="text-lg font-semibold text-gray-800 dark:text-slate-100 mb-2 wrap-break-word">
            {{ task.text }}
          </h3>
          <p class="text-sm text-gray-600 dark:text-slate-300 flex items-center gap-2">
            <i class="pi pi-calendar text-blue-600 dark:text-blue-400"></i>
            {{ formatDate(task.day) }}
          </p>
          <div v-if="task.reminder" class="mt-2 flex items-center gap-2">
            <i class="pi pi-bell text-amber-500"></i>
            <span class="text-xs text-amber-600 dark:text-amber-400 font-medium">Reminder Set</span>
          </div>
        </div>
        <Button
          icon="pi pi-times"
          rounded
          text
          severity="danger"
          @click="deleteTask"
          v-tooltip.left="'Delete task'"
          class="shrink-0"
        />
      </div>
    </template>
  </Card>
</template>

<style scoped>
.reminder {
  border-left: 4px solid #f59e0b;
}
</style>
