// apps/react-tracker/src/components/tasks/TaskForm.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';
import { Button } from 'primereact/button';
import { Calendar } from 'primereact/calendar';
import { Checkbox } from 'primereact/checkbox';
import { taskService } from '../../services/task.service';
import type { Task } from '@task-domain';

export const TaskForm = () => {
  const navigate = useNavigate();

  const [taskText, setTaskText] = useState('');
  const [taskDate, setTaskDate] = useState<Date>(new Date());
  const [taskReminder, setTaskReminder] = useState(false);

  const cancelAddTask = () => {
    navigate('/');
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!taskText || !taskDate) {
      alert('Please fill all fields');
      return;
    }

    const newTask: Task = {
      id: uuidv4(),
      text: taskText,
      day: taskDate.toISOString(),
      reminder: taskReminder,
    };

    try {
      await taskService.addTask(newTask);
      navigate('/');
    } catch (error) {
      console.error('Failed to add task:', error);
      alert('Failed to add task. Please try again.');
    }
  };

  return (
    <div className="px-6 py-8">
      <h2 className="text-2xl font-bold text-gray-800 dark:text-slate-100 mb-6">Add New Task</h2>
      <form
        onSubmit={onSubmit}
        data-test-id="add-task-form"
        className="space-y-6 bg-white dark:bg-slate-900 p-6 rounded-lg shadow-md"
      >
        <div className="form-field">
          <label
            htmlFor="text"
            data-testid="label-task"
            className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Task Description
          </label>
          <input
            id="text"
            value={taskText}
            onChange={(e) => setTaskText(e.target.value)}
            type="text"
            placeholder="Enter task description"
            data-test-id="input-task"
            className="p-inputtext p-component w-full"
          />
        </div>

        <div className="form-field">
          <label
            htmlFor="date"
            data-test-id="label-date"
            className="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Due Date
          </label>
          <Calendar
            id="date"
            value={taskDate}
            onChange={(e) => setTaskDate(e.value as Date)}
            showIcon
            className="w-full"
            showTime
            hourFormat="12"
          />
        </div>

        <div className="form-field flex items-center gap-3 p-4 bg-gray-50 dark:bg-slate-800 rounded-lg">
          <Checkbox
            inputId="reminder"
            checked={taskReminder}
            onChange={(e) => setTaskReminder(e.checked ?? false)}
            data-test-id="input-reminder"
            className="w-5 h-5"
          />
          <label
            htmlFor="reminder"
            data-test-id="label-reminder"
            className="text-sm font-medium text-gray-700 dark:text-slate-300 cursor-pointer"
          >
            Set Reminder
          </label>
        </div>

        <div className="flex gap-4 pt-4">
          <Button
            className="flex-1"
            data-test-id="input-cancel-task"
            label="Cancel"
            id="cancelButton"
            onClick={cancelAddTask}
            severity="secondary"
            outlined
            type="button"
          />
          <Button
            className="flex-1"
            data-test-id="input-save-task"
            label="Save Task"
            id="submitButton"
            type="submit"
            severity="success"
            icon="pi pi-check"
          />
        </div>
      </form>
    </div>
  );
};

// apps/ng-tracker/src/app/modules/add-task/components/task-form.component.ts
import { Component } from '@angular/core';
import { Task } from '@task-domain';
import { FormBuilder, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { TaskService } from '../../../shared/services/task.service';
import { v4 as uuidv4 } from 'uuid';
import { tap } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { DatePickerModule } from 'primeng/datepicker';

@Component({
  selector: 'app-task-form',
  imports: [
    FormsModule,
    ReactiveFormsModule,
    ButtonModule,
    InputTextModule,
    DatePickerModule,
  ],
  template: `
    <div class="px-6 py-8">
      <h2 class="text-2xl font-bold text-gray-800 dark:text-slate-100 mb-6">
        Add New Task
      </h2>
      <form
        [formGroup]="taskForm"
        (ngSubmit)="onSubmit()"
        data-test-id="add-task-form"
        class="space-y-6 bg-white dark:bg-slate-900 p-6 rounded-lg shadow-md"
      >
        <div class="form-field">
          <label
            for="text"
            data-testid="label-task"
            class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Task Description
          </label>
          <input
            type="text"
            name="text"
            formControlName="text"
            id="text"
            placeholder="Enter task description"
            data-test-id="input-task"
            pInputText
            class="w-full"
          />
        </div>

        <div class="form-field">
          <label
            for="date"
            data-test-id="label-date"
            class="block text-sm font-medium text-gray-700 dark:text-slate-300 mb-2"
          >
            Due Date
          </label>
          <p-datepicker
            formControlName="date"
            [showIcon]="true"
            appendTo="body"
            inputId="date"
            class="w-full"
          />
        </div>

        <div
          class="form-field flex items-center gap-3 p-4 bg-gray-50 dark:bg-slate-800 rounded-lg"
        >
          <input
            data-test-id="input-reminder"
            type="checkbox"
            name="reminder"
            formControlName="reminder"
            id="reminder"
            class="w-5 h-5 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 focus:ring-2"
          />
          <label
            for="reminder"
            data-test-id="label-reminder"
            class="text-sm font-medium text-gray-700 dark:text-slate-300 cursor-pointer"
          >
            Set Reminder
          </label>
        </div>

        <div class="flex gap-4 pt-4">
          <p-button
            class="flex-1"
            data-test-id="input-cancel-task"
            label="Cancel"
            id="cancelButton"
            (click)="cancelAddTask()"
            severity="secondary"
            [outlined]="true"
          />
          <p-button
            class="flex-1"
            data-test-id="input-save-task"
            label="Save Task"
            id="submitButton"
            type="submit"
            severity="success"
            icon="pi pi-check"
          />
        </div>
      </form>
    </div>
  `,
})
export class TaskFormComponent {
  taskForm = this.fb.group({
    text: [''],
    date: [new Date()],
    reminder: [false],
  });

  constructor(
    private readonly fb: FormBuilder,
    private readonly router: Router,
    private readonly taskService: TaskService,
  ) {}

  cancelAddTask() {
    this.router.navigate(['/']);
  }

  onSubmit() {
    if (!this.taskForm.value.text || !this.taskForm.value.date) {
      alert('Please fill all fields');
      return;
    }

    const newTask: Task = {
      id: uuidv4(),
      text: this.taskForm.value.text,
      day: this.taskForm.value.date?.toISOString() ?? '',
      reminder: this.taskForm.value.reminder || false,
    };

    this.taskService
      .addTask(newTask)
      .pipe(
        tap(() => {
          this.router.navigate(['/']);
        }),
      )
      .subscribe();
  }
}
